[package]
name = "mp4dase"
version = "0.1.0"
edition = "2021"
publish = ["crates-io"]
authors = ["Thiago Pontes <crates@thiago.me>"]

[dependencies]
bytes = "1.6.0"
log = "0.4.21"

[dev-dependencies]
env_logger = "0.11.3"
